### PR TITLE
Missing package

### PR DESCRIPTION
**Pull request by pgraverdy**
Adds missing datclasses requirement

### CODE REVIEW

**Comment by pgraverdy** [comment]
Sorry, went a bit too quikly on that PR. Will fix first.

**Comment by rth** [comment]
I think we are Python 3.7+ where https://docs.python.org/3.7/library/dataclasses.html is part of the stdlib?

**Comment by dulacarnold** [comment]
I can confirm we are not compatible with python_version < 3.7.

**Comment by dulacarnold** [comment]
@pgraverdy are you able to build w/out this if you use python>3.7?

**Pull request closed without merging**
