### PR TITLE
Added email field to users table.

### PR DESCRIPTION
**Pull request by sgirgin**
We are not using it yet.

### CODE REVIEW

**Comment by dulacarnold** [comment]
Hey Sertan, nice, since there is a DB migration step, do you think you could also add the following:
Column("n_ncovid_free", Integer), in bed_updates
And a boolean column 'active' that defaults to True to icus?

Normally I would prefer a seperate PR but because of the migration it might be easier to push all these changes at once.

**Comment by sgirgin** [comment]
> n_ncovid_free

Sure, done.

**Comment by dulacarnold** [comment]
I'm sorry, I got lost, we already have n_ncovid_free, we need to add n_ncovid_occ.  Sorry about that!  Otherwise LGTM.

**Comment by sgirgin** [comment]
No worries, we probably don't need this change since it will be superseded
by the store.

**Pull request closed without merging**
