### PR TITLE
fix predicu export script

### PR DESCRIPTION
**Pull request by tgy**

### CODE REVIEW

**Comment by rth** [comment]
Should we add a unit test for the export function? E.g. monekypatch bedcount data with fake data as done in the plot tests? Currently it's not tested at all.

**Comment by dulacarnold** [comment]
Codecov is blocking this, is that WAI?

**Comment by rth** [comment]
It's blocking because `export_data` has no tests. We can still merge regardless but it would be nice to add a test.

**Comment by tgy** [comment]
@rth I've added a test but the monkey patching does not seem to work.

could you check it out?

**Pull request merged**
