### PR TITLE
Added isort to .precommit

### PR DESCRIPTION
**Pull request by dulacarnold**

### CODE REVIEW

**Comment by maximedenes** [comment]
@dulacarnold the pre-commit hook seems to error when imports are not well sorted. How to make it sort them properly?

**Comment by rth** [comment]
You need to run `git commit` twice. The first time it will sort them (same for yapf).

**Comment by maximedenes** [comment]
Hmmm, it seems to fail even when I retry. What could I be doing wrong?

**Comment by maximedenes** [comment]
Note that for yapf, yes, it works if I try a second time.

**Comment by rth** [comment]
I haven't used isort much before, maybe you hit an issue in compatibility between yapf and isort. For instance, https://github.com/timothycrosley/isort/pull/1172 is one. I also tried it on another project recently and also got some strange behavior from isort. 

isort is nice, but if we spend too much time getting contradicting errors maybe it it's not worth it.

What's the output of `git diff` before and after isort errors? Or what are the error in general?

**Comment by maximedenes** [comment]
The errors are:
```
ERROR: /home/mdenes/dev/icubam/icubam/predicu/plot/__init__.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/db/store.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/backoffice/server.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/www/handlers/base.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/db/synchronizer.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/backoffice/handlers/operational_dashboard.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/backoffice/handlers/upload.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/map_builder.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/messaging/handlers/schedule.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/backoffice/handlers/tokens.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/backoffice/handlers/base.py Imports are incorrectly sorted.
ERROR: /home/mdenes/dev/icubam/icubam/www/updater.py Imports are incorrectly sorted.
```

In the first file, I don't even touch the imports... And `isort` does not seem to be changing my changes in any way.

I keep try `git commit`, yapf does not say anything at this point, so I don't think that's an incompatibility. It looks more like `isort` is just not try to fix the errors. Did you confirm on your setup it was fixing errors automatically?

**Comment by rth** [comment]
Yes you are right we need to remove `-c` (`--check`) argument if we want to do it automatically. I'm not sure if that flag was intentional or not.

**Pull request merged**
